providers:
  - id: watsonx:ibm/granite-13b-chat-v2

prompts:
  - "Answer the following question: '{{question}}'"

tests:
  - vars:
      question: "What is the capital of France?"
    assert:
      - type: contains
        value: "Paris"

  - vars:
      question: "What is 2 + 2?"
    assert:
      - type: contains
        value: "4"

  - vars:
      question: "Is the sky blue?"
    assert:
      - type: contains
        value: "yes"

  - vars:
      question: "Who wrote 'Romeo and Juliet'?"
    assert:
      - type: contains
        value: "William Shakespeare"

  - vars:
      question: "How many continents are there on Earth?"
    assert:
      - type: contains
        value: "seven"