# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: 'WatsonX eval'

prompts:
  - 'Write a funny tweet about {{topic}}'
  - 'Make a joke in a tweet about {{topic}}'

providers:
  - 'watsonx:meta-llama/llama-3-2-11b-vision-instruct'
  - 'watsonx:ibm/granite-13b-chat-v2'

tests:
  - vars:
      topic: bananas

  - vars:
      topic: avocado toast
    assert:
      # For more information on assertions, see https://promptfoo.dev/docs/configuration/expected-outputs

      # Make sure output contains the word "avocado"
      - type: icontains
        value: avocado

      # Prefer shorter outputs
      - type: javascript
        value: 1 / (output.length + 1)

  - vars:
      topic: new york city
    assert:
      # For more information on model-graded evals, see https://promptfoo.dev/docs/configuration/expected-outputs/model-graded
      - type: llm-rubric
        value: ensure that the tweet contains a pun, joke, or sarcastic remark
